'on':
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  run-tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        pg_version:
          - 16
    services:
      postgres:
        image: 'postgres:${{ matrix.pg_version }}'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v3
      - name: Clone and shift tests
        run: cd src/workflow_utils && chmod +x setup.sh && ./setup.sh
      - name: check_val
        run: ls src/ && ls ../
      - uses: actions/upload-artifact@v4
        with:
          name: test-log
          path: ./src/final_report.log
      - uses: actions/upload-artifact@v4
        with:
          name: broken-links
          path: ./src/broken_urls.log
      - uses: actions/upload-artifact@v4
        with:
          name: failure_logs
          path: ./src/failed_tests.log

      - name: Send notification email
        env:
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
        run: python ./src/workflow_utils/send_mail.py

  run-acc-tests:
      runs-on: ubuntu-20.04
      strategy:
        matrix:
          pg_version:
            - 15
      services:
        postgres:
          image: 'postgres:${{ matrix.pg_version }}'
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
          ports:
            - '5432:5432'
          options: >-
            --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      steps:
        - name: Checkout Current Repository
          uses: actions/checkout@v3
        - name: Clone and shift tests
          run: cd src/workflow_utils && chmod +x accessibility-setup.sh && ./accessibility-setup.sh
        - name: check_val
          run: ls src/ && ls ../
        - uses: actions/upload-artifact@v4
          with:
            name: accessibility-tests
            path: |
              ./src/acc_reports/
     
